### ISSUE TITLE
About the Icons

### ISSUE THREAD

**Issue by ahmadawais** [softvar/github-plus#4]
@s0ftvar Nice one. It's a bit buggy, though. Downloading dotfiles convert them to something like gitignore.txt. Also, can you downtone these icons to be grey in color and a bit more minimal icons? Like this http://cloud.ahmda.ws/rYOl31L so that the UI doesn't feel overwhelming? 

I think `#999` color would do. 
A bit padding-left would be great. Something like http://cloud.ahmda.ws/Yc8AbJ1
Thanks!

**Comment by softvar** [comment]
👍 
This is a nice thought!
Thanks for the suggestion!

As per the screenshot, it appears that you have already done the desired thing, though maybe with just the developer tools. PR? 😆 

Any thoughts regarding dealing with the dotfiles fix?

Thanks @ahmadawais !

**Comment by softvar** [comment]
I have asked the dotfiles issue question on StackOverflow after trying a lot of ways to handle that.
http://stackoverflow.com/questions/38931933/download-dotfile-using-html5-download-preserving-name

**Comment by ahmadawais** [comment]
@softvar I haven't read the source but I can push a PR tonight, could you point me in the right direction to where should I add the CSS? To which file in this repo? I am new to Chrome extensions, though, I know a few basics like the manifest file etc.

**Comment by ahmadawais** [comment]
Not sure about dotfiles though. Will look into it.

**Comment by softvar** [comment]
@ahmadawais 
Just checked https://www.w3.org/TR/html5/links.html#downloading-resources
and according to point no. 19 - 

```
If the claimed type is known, then alter filename to add an extension corresponding to claimed type.

Otherwise, if named type is known to be potentially dangerous (e.g. it will be treated by the platform conventions as a native executable, shell script, HTML application, or executable-macro-capable document) then optionally alter filename to add a known-safe extension (e.g. ".txt").
```

**Comment by ahmadawais** [comment]
@softvar So, there ain't a way around it?

**Comment by ahmadawais** [comment]
@softvar Check the PR 💯

**Comment by softvar** [comment]
@ahmadawais I talked with other UI guys around me, it turns out that blue color is much more prominent than the default grayish color.
The Blue color actually implies there's something actionable and is.

Consider this screenshot - https://www.dropbox.com/s/g4ia0kybn7vinqa/Screenshot%202016-10-27%2016.29.07.png?dl=0 , anything which is clickable turns blue on hover to indicate some action. Here, as you earlier mentioned, we don't' have any way to add pseudo classes, so I think it's better to show download icon in blue color by default to let a user know of its implication.

Thanks for the patch, though.

**Comment by ahmadawais** [comment]
^That is the hover state not the general state. Anywho, I'll just fork the extension then.
